name: ci

on:
  push:
    branches:
      - test-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-verify:
    name: Build and verify
    runs-on: [self-hosted, linux, arm64]
    steps:
      - run: echo "Hello, runners!"
